{% set version = "0.6.1" %}

package:
  name: adlfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/adlfs/adlfs-{{ version }}.tar.gz
  sha256: 22dc0405bc0342e8a78e7f50cac0634b95d67984d719513eac806dc2c5ec2c0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - aiohttp
    - azure-core >=1.5.0
    - azure-datalake-store >=0.0.46,<0.1
    - azure-identity
    - azure-storage-blob >=12.5.0,<12.7.0
    - fsspec >=0.8.2
    - msrestazure
    - requests >=2.22.0,<3.0

test:
  imports:
    - adlfs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/adlfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: fsspec-compatible Azure Datalake and Azure Blob Storage access

extra:
  recipe-maintainers:
    - hayesgb
    - martindurant
    - TomAugspurger
    - raybellwaves
