{% set version = "0.3.1" %}

package:
  name: adlfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/adlfs/adlfs-{{ version }}.tar.gz
  sha256: 613460bf970f36b572b8d267ff87c8b9bd21b2c0c768b7ae1b5608d69102d19c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - azure-core >=1.5.0
    - azure-datalake-store >=0.0.46,<0.1
    - azure-storage-blob >=12.0.0
    - fsspec >=0.6.0

test:
  imports:
    - adlfs

about:
  home: https://github.com/dask/adlfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: fsspec-compatible Azure Datalake and Azure Blob Storage access

extra:
  recipe-maintainers:
    - hayesgb
    - martindurant
    - raybellwaves
